// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTSFNuavjaaZBY2K3r-zO59e6pTLjw-PA',
    appId: '1:921241632329:android:791589ccfc76b244920998',
    messagingSenderId: '921241632329',
    projectId: 'fir-auth-17756',
    storageBucket: 'fir-auth-17756.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkn8_dNxsJknlqfqhOm3TbvnxqUHOIsl0',
    appId: '1:921241632329:ios:678f1ac837264d84920998',
    messagingSenderId: '921241632329',
    projectId: 'fir-auth-17756',
    storageBucket: 'fir-auth-17756.appspot.com',
    androidClientId: '921241632329-8gnb1gm4idi3m5k4nes6c9rg54nskrpl.apps.googleusercontent.com',
    iosClientId: '921241632329-n8886fve7unsribsetu5dkpcl65p27nn.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuth',
  );
}
